// <auto-generated />
using System;
using ArchiveWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchiveWeb.Migrations
{
    [DbContext(typeof(ArchiveDbContext))]
    [Migration("20251224161349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsBudgetFinancing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOriginalSubmitted")
                        .HasColumnType("boolean");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudyForm")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_applicant_email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("idx_applicant_phone");

                    b.ToTable("applicants", (string)null);
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.ArchiveConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdaptiveRedistributionThreshold")
                        .HasColumnType("integer");

                    b.Property<double>("AdaptiveWeightNew")
                        .HasColumnType("double precision");

                    b.Property<double>("AdaptiveWeightOld")
                        .HasColumnType("double precision");

                    b.Property<int>("BoxCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("BoxCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PercentDeletedFiles")
                        .HasColumnType("integer");

                    b.Property<int>("PercentReservedFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("archive_configurations", (string)null);
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.ArchiveHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileArchiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NewBoxId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NewBoxNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NewLetterId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NewPosition")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OldBoxId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OldBoxNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OldLetterId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OldPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_archive_history_created_at");

                    b.HasIndex("FileArchiveId")
                        .HasDatabaseName("idx_archive_history_file_id");

                    b.HasIndex("NewBoxId");

                    b.HasIndex("NewLetterId");

                    b.ToTable("archive_history", (string)null);
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("uk_box_number");

                    b.ToTable("boxes", (string)null);
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.FileArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileNumberForArchive")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("FileNumberForLetter")
                        .HasColumnType("integer");

                    b.Property<char>("FirstLetterSurname")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid");

                    b.Property<int>("PositionInBox")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique()
                        .HasDatabaseName("uk_applicant");

                    b.HasIndex("BoxId")
                        .HasDatabaseName("idx_file_archives_box_id");

                    b.HasIndex("FirstLetterSurname")
                        .HasDatabaseName("idx_file_archives_letterValue");

                    b.HasIndex("FullName")
                        .HasDatabaseName("idx_file_archives_fullName");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_file_archives_is_deleted");

                    b.HasIndex("LetterId")
                        .HasDatabaseName("idx_file_archives_letter_id");

                    b.ToTable("file_archives", (string)null);
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.Letter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndBox")
                        .HasColumnType("integer");

                    b.Property<int?>("EndPosition")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("StartBox")
                        .HasColumnType("integer");

                    b.Property<int?>("StartPosition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<char>("Value")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("uk_letter_value");

                    b.ToTable("letters", (string)null);
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.ArchiveHistory", b =>
                {
                    b.HasOne("ArchiveWeb.Domain.Entities.FileArchive", "FileArchive")
                        .WithMany("History")
                        .HasForeignKey("FileArchiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArchiveWeb.Domain.Entities.Box", "ActualBox")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("NewBoxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveWeb.Domain.Entities.Letter", "ActualLetter")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("NewLetterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActualBox");

                    b.Navigation("ActualLetter");

                    b.Navigation("FileArchive");
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.FileArchive", b =>
                {
                    b.HasOne("ArchiveWeb.Domain.Entities.Applicant", "Applicant")
                        .WithOne("FileArchive")
                        .HasForeignKey("ArchiveWeb.Domain.Entities.FileArchive", "ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArchiveWeb.Domain.Entities.Box", "Box")
                        .WithMany("FileArchives")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveWeb.Domain.Entities.Letter", "Letter")
                        .WithMany("FileArchives")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Box");

                    b.Navigation("Letter");
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.Applicant", b =>
                {
                    b.Navigation("FileArchive");
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.Box", b =>
                {
                    b.Navigation("FileArchives");

                    b.Navigation("HistoryEntries");
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.FileArchive", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ArchiveWeb.Domain.Entities.Letter", b =>
                {
                    b.Navigation("FileArchives");

                    b.Navigation("HistoryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
